config/routes.rb
Aetg::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  
  namespace :admin do
     root :to => "portal#index"
     match 'login' => 'portal#login'
     match 'logout' => 'portal#logout', :as => 'logout_admin_user'
     match 'dashboard' => 'portal#index'
     resources :users
     match 'users/new' => 'users#new'
     resources :locales
     resources :seo
     match 'project_images/:id/project' => 'project_images#specific_project'
     match 'project_videos/:id/project' => 'project_videos#specific_project'

     resources :topbanners
     
     resources :pages
     resources :design_templates
     resources :branches
     resources :partners
     resources :teams
     resources :content_images
     resources :job_posts
     resources :companies
     resources :job_industries
     resources :job_classifications
     resources :job_posts
     resources :positions
   end
   
    devise_for :members, :controllers => {  :registrations => "members/registrations", :sessions => "members/sessions"} #,:unlocks => "members/unlocks", :passwords => "members/passwords", :confirmations => "members/confirmations", :omniauth_callbacks => "members/omniauth_callbacks" }
    
    match '/searchers' => 'search#index'
    match '/organization' => 'people#organization_index'
    match 'home' => 'home#index'
    match 'about_us' => 'about_us#show'
    match 'about_us/:page_url' => 'about_us#show'
    match 'our_services' => 'services#show'
    match 'our_team' => 'teams#index'
    match 'our_team/:page_url' => 'teams#show'
    match 'our_practices' => 'practices#show'
    match 'our_practices/(:page_url)' => 'practices#show', :constraints => { :page_url => /.*/ }
    match 'our_stories' => 'stories#show'
    match 'our_stories/:page_url' => 'stories#show'
    match 'our_advantages' => 'advantages#show'
    match 'our_advantages/:page_url' => 'advantages#show'
    match 'opportunities' => 'opportunities#list', :as => 'job_posts'
    match 'opportunities/show/:id' => 'opportunities#show'
    match 'opportunities/display/:id' => 'opportunities#display'
    match 'opportunities/industry/:industry_id' => 'opportunities#browse'
    match 'contact_us' => 'contact_us#show'
      
      
   scope ':locale' do
    
   end
   
   
   root :to => 'home#index'
   match '/:locale' => 'home#change_locale'
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  include Admin::AdministratorModule
  before_filter :set_title
  before_filter :check_role, :only => [:destroy]

  def check_role
    if session[:admin_role] != 'Admin'
      @projects = Project.all#.paginate(:page => params[:page])
      redirect_to(:action => "index", :warning => 'You are not allow to do this action!')
    end
  end
  
  def set_title
    @title = "Projects Management"
  end
  
  def index
    session[:current_page_name] = 'Projects'
    @projects = Project.all#.paginate(:page => params[:page])
  end
  
  def show
    #@user = User.find(params[:id])
    @projects = Project.all#.paginate(:page => params[:page])
    render :action => "index"
  end
  
  def new
    @title = "Add Project"
    @projects = Project.new
  end
  
  def edit
    @title = "Edit Project"
    @projects = Project.find(params[:id])
  end
  
  def create
    @projects = Project.new(params[:projects])
    if @projects.save
      redirect_to(:url => admin_project_path(@projects), :notice => 'Create Project Successfully!')
    else
      render :action => "new"
    end
  end
  
  def update
    @projects = Project.find(params[:id])
    @projects.last_updated_by = session[:admin_username]
    if @projects.update_attributes(params[:projects].reject{|k,v| v.blank?})
      
      redirect_to(:url => admin_project_path, :notice => 'Update Project Successfully!')
    else
      render :action => "edit"
    end
  end

  def destroy
    @projects = Project.find(params[:id])
    @projects.destroy
    
    redirect_to(admin_projects_path)
  end
end

app/views/admin/projects/edit.html.erb
<% content_for :header_meta do%>
<!-- // Meta //  -->
<meta charset="utf-8">   
<meta name="description" content="" />
<meta name="keywords" content="" />

<% end %>
<% content_for :content do %>
	<%= form_for(@projects, :as => :projects, :validate => true, :url => admin_project_path(@projects)) do |f| %>
	
	   <fieldset>
	        <legend><h2>Edit Project</h2></legend>

	        <dl>
				<dt>
	                <label>Url Title</label>
	            </dt>
	            <dd>
					<%= f.text_field :url_title, :class => 'small' %>  
	            </dd>
				<dt>
	                <label>Browser Title</label>
	            </dt>
	            <dd>
					<%= f.text_field :browser_title, :class => 'small' %>  
	            </dd>
				<dt>
	                <label>Project Name</label>
	            </dt>
	            <dd>
					<%= f.text_field :title, :class => 'small' %>  
	            </dd>
				
				<dt>
	                <label>Company Name</label>
	            </dt>
	            <dd>
					<%= f.text_field :company, :class => 'small' %>  
	            </dd>
				

	            <dt>
	                <label>Description</label>   
	            </dt>

	            <dd>
	                <%= f.text_area :description, :rows => 6, :cols => 80%>  
	            </dd>

	            <dt>
	                <label>Tag</label>
	            </dt>
	            <dd>
					<%= f.text_field :tag, :class => 'large' %>  
	            </dd>

			</dl>
		</fieldset>
		<fieldset>
		        <legend><h2>Settings</h2></legend>

		        <dl>
					<dt>
		                <label>Publish Date</label>
		            </dt>
		            <dd>
						<%= f.text_field :publish_date, :class => 'datepicker small'  %>
		            </dd>
					<dt>
		                <label>Locale</label>
		            </dt>
		            <dd>
						<% @collectionSet = Locale.all%>
	                    <%= f.collection_select :locale, @collectionSet, :code, :name, {:include_blank => true}, {:class => 'select-1'} %>
		            </dd>
					<dt>
		                <label>Is Published?</label>
		            </dt>
		            <dd>
						<%= f.check_box :activate  %>
		            </dd>
		        </dl>
	        <p>
	            <button type="submit" value="Save">Submit</button> or <a href="/admin/<%= session[:current_page_name].downcase %>" title="Leave without saving" rel="tooltip">Cancel</a>
	        </p>
	        <br />

	    </fieldset>
	<% end %>
	<div>
	    <a href="/admin/<%= session[:current_page_name].downcase %>">Back to List</a>
	</div>
<% end %>

app/views/admin/projects/index.html.erb
<% content_for :header_meta do%>
<!-- // Meta //  -->
<meta charset="utf-8">   
<meta name="description" content="" />
<meta name="keywords" content="" />

<% end %>

<% content_for :content do %>
<article class="full-block clearfix">
		
			<div class="article-container">
            <section>
				<% if params[:notice] %>
					<div class="notification success">
						<a href="#" class="close-notification" title="Hide Notification" rel="tooltip">x</a>
						<p><strong>Success notification:</strong> <%= params[:notice] %></p>
					</div>
				<% end %>
				<% if params[:warning] %>
					<div class="notification error">
						<a href="#" class="close-notification" title="Hide Notification" rel="tooltip">x</a>
						<p><strong>Error notification:</strong> <%= params[:warning] %></p>
					</div>
				<% end %>
	
	
					<div class="sidetab default-sidetab" id="sidetab1">
							<h3>List of Projects</h3>
                            <p>
                                <%= link_to "Create New", new_admin_project_path %>
                            </p>
							<table class="datatable">
								<thead>
									 <tr>
                                        <th>
                                            Project Name
                                        </th>
										<th>
											Tag
										</th>
                                        <th>
                                            Locale
                                        </th>
                                        <th>
                                            Created At
                                        </th>
										<th>
                                            Is Published?
                                        </th>
                                        <th></th>
                                    </tr>
								</thead>
								<tbody>
									<% for project in @projects %>
									<tr class="gradeX">
										<td><%= project.title %></td>
										<td><%= project.tag %></td>
										<td><%= project.locale %></td>
										<td><%= project.created_at.strftime("%m-%d-%Y") %></td>
										<td>
											<% if project.activate == true %>
												<%= image_tag 'admin/img/icons/list-style/icon_list_style_checkmark.png' %>
											<% else %>
												<%= image_tag 'admin/img/icons/list-style/icon_list_style_cross.png' %>
											<% end %>
										</td>
										<td><a href="/admin/project_images/<%= project.id %>/project">Manage Image</a> | <a href="/admin/project_videos/<%= project.id %>/project">Manage Video</a> | <%= link_to "Edit", edit_admin_project_path(project) %> |
                                        <%= link_to "Delete", admin_project_path(project), :confirm => 'Are you sure?', :method => :delete, :title => "Delete" %></td>
										
									</tr>
									<% end %>
									
								</tbody>
								<tfoot>
									<tr>
										<th>
                                            Project Name
                                        </th>
										<th>
											Tag
										</th>
                                        <th>
                                            Locale
                                        </th>
                                        <th>
                                            Created At
                                        </th>
										<th>
                                            Is Published?
                                        </th>
                                        <th></th>
									</tr>
								</tfoot>
							</table>
</div>
</section>
</div>
</article>
<% end %>

app/views/admin/projects/new.html.erb
<% content_for :header_meta do%>
<!-- // Meta //  -->
<meta charset="utf-8">   
<meta name="description" content="" />
<meta name="keywords" content="" />

<% end %>
<% content_for :content do %>
	<%= form_for(@projects, :as => :projects, :validate => true, :url => admin_projects_path) do |f| %>
	
	   <fieldset>
	        <legend><h2>Create Project</h2></legend>

	        <dl>
				<dt>
	                <label>Url Title</label>
	            </dt>
	            <dd>
					<%= f.text_field :url_title, :class => 'small' %>  
	            </dd>
				<dt>
	                <label>Browser Title</label>
	            </dt>
	            <dd>
					<%= f.text_field :browser_title, :class => 'small' %>  
	            </dd>
				<dt>
	                <label>Project Name</label>
	            </dt>
	            <dd>
					<%= f.text_field :title, :class => 'small' %>  
	            </dd>
				
				<dt>
	                <label>Company Name</label>
	            </dt>
	            <dd>
					<%= f.text_field :company, :class => 'small' %>  
	            </dd>

	            <dt>
	                <label>Description</label>   
	            </dt>

	            <dd>
	                <%= f.text_area :description, :rows => 6, :cols => 80%>  
	            </dd>

	            <dt>
	                <label>Tag</label>
	            </dt>
	            <dd>
					<%= f.text_field :tag, :class => 'large' %>  
	            </dd>

			</dl>
		</fieldset>
		<fieldset>
		        <legend><h2>Settings</h2></legend>

		        <dl>
					<dt>
		                <label>Publish Date</label>
		            </dt>
		            <dd>
						<%= f.text_field :publish_date, :class => 'datepicker small'  %>
		            </dd>
					<dt>
		                <label>Locale</label>
		            </dt>
		            <dd>
						<% @collectionSet = Locale.all%>
	                    <%= f.collection_select :locale, @collectionSet, :code, :name, {:include_blank => true}, {:class => 'select-1'} %>
		            </dd>
					<dt>
		                <label>Is Published?</label>
		            </dt>
		            <dd>
						<%= f.check_box :activate  %>
		            </dd>
		        </dl>
	        <p>
	            <button type="submit" value="Save">Submit</button> or <a href="/admin/<%= session[:current_page_name].downcase %>" title="Leave without saving" rel="tooltip">Cancel</a>
	        </p>
	        <br />

	    </fieldset>
	<% end %>
	<div>
	    <a href="/admin/<%= session[:current_page_name].downcase %>">Back to List</a>
	</div>
<% end %>