config/routes.rb
Aetg::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  
  namespace :admin do
     root :to => "portal#index"
     match 'login' => 'portal#login'
     match 'logout' => 'portal#logout', :as => 'logout_admin_user'
     match 'dashboard' => 'portal#index'
     resources :users
     match 'users/new' => 'users#new'
     resources :locales
     resources :seo
     match 'project_images/:id/project' => 'project_images#specific_project'
     match 'project_videos/:id/project' => 'project_videos#specific_project'

     resources :topbanners
     
     resources :pages
     resources :design_templates
     resources :branches
     resources :partners
     resources :teams
     resources :content_images
     resources :job_posts
     resources :companies
     resources :job_industries
     resources :job_classifications
     resources :job_posts
     resources :positions
   end
   
    devise_for :members, :controllers => {  :registrations => "members/registrations", :sessions => "members/sessions"} #,:unlocks => "members/unlocks", :passwords => "members/passwords", :confirmations => "members/confirmations", :omniauth_callbacks => "members/omniauth_callbacks" }
    
    match '/searchers' => 'search#index'
    match '/organization' => 'people#organization_index'
    match 'home' => 'home#index'
    match 'about_us' => 'about_us#show'
    match 'about_us/:page_url' => 'about_us#show'
    match 'our_services' => 'services#show'
    match 'our_team' => 'teams#index'
    match 'our_team/:page_url' => 'teams#show'
    match 'our_practices' => 'practices#show'
    match 'our_practices/(:page_url)' => 'practices#show', :constraints => { :page_url => /.*/ }
    match 'our_stories' => 'stories#show'
    match 'our_stories/:page_url' => 'stories#show'
    match 'our_advantages' => 'advantages#show'
    match 'our_advantages/:page_url' => 'advantages#show'
    match 'opportunities' => 'opportunities#list', :as => 'job_posts'
    match 'opportunities/show/:id' => 'opportunities#show'
    match 'opportunities/display/:id' => 'opportunities#display'
    match 'opportunities/industry/:industry_id' => 'opportunities#browse'
    match 'contact_us' => 'contact_us#show'
      
      
   scope ':locale' do
    
   end
   
   
   root :to => 'home#index'
   match '/:locale' => 'home#change_locale'
end

app/models/design_template.rb
class DesignTemplate < ActiveRecord::Base
end

app/controllers/admin/design_templates_controller.rb
class Admin::DesignTemplatesController < ApplicationController
  include Admin::AdministratorModule
  before_filter :set_title
  before_filter :check_role, :only => [:new, :create, :destroy]

  def check_role
    if session[:admin_role] != 'Admin'
      @design_template = DesignTemplate.all#.paginate(:page => params[:page])
      redirect_to(:action => "index", :warning => 'You are not allow to do this action!')
    end
  end
  
  def set_title
    @title = "Design Template Management"
  end
  
  def index
    session[:current_page_name] = 'Design Templates'
    @design_template = DesignTemplate.all#.paginate(:page => params[:page])
  end
  
  def show
    #@user = User.find(params[:id])
    @design_template = DesignTemplate.all#.paginate(:page => params[:page])
    render :action => "index"
  end
  
  def new
    @title = "Add Design Template"
    @design_template = DesignTemplate.new
  end
  
  def edit
    @title = "Edit Design Template"
    @design_template = DesignTemplate.find(params[:id])
  end
  
  def create
    @design_template = DesignTemplate.new(params[:design_template])
    if @design_template.save
      redirect_to(:url => admin_design_template_path(@design_template), :notice => 'Create Design Template Successfully!')
    else
      render :action => "new"
    end
  end
  
  def update
    @design_template = DesignTemplate.find(params[:id])
    @design_template.last_updated_by = session[:admin_username]
    if @design_template.update_attributes(params[:design_template].reject{|k,v| v.blank?})
      
      redirect_to(:url => admin_design_template_path, :notice => 'Update Design Template Successfully!')
    else
      render :action => "edit"
    end
  end

  def destroy
    @design_template = DesignTemplate.find(params[:id])
    @design_template.destroy
    
    redirect_to(admin_design_templates_path)
  end
  
end

app/helpers/admin/design_templates_helper.rb
module Admin::DesignTemplatesHelper
end

app/views/admin/design_templates/index.html.erb
<% content_for :header_meta do%>
<!-- // Meta //  -->
<meta charset="utf-8">   
<meta name="description" content="" />
<meta name="keywords" content="" />

<% end %>

<% content_for :content do %>
<article class="full-block clearfix">
		
			<div class="article-container">
            <section>
				<% if params[:notice] %>
					<div class="notification success">
						<a href="#" class="close-notification" title="Hide Notification" rel="tooltip">x</a>
						<p><strong>Success notification:</strong> <%= params[:notice] %></p>
					</div>
				<% end %>
				<% if params[:warning] %>
					<div class="notification error">
						<a href="#" class="close-notification" title="Hide Notification" rel="tooltip">x</a>
						<p><strong>Error notification:</strong> <%= params[:warning] %></p>
					</div>
				<% end %>
	
	
					<div class="sidetab default-sidetab" id="sidetab1">
							<h3>List of Design Templates</h3>
                            <p>
                                <%= link_to "Create New", new_admin_design_template_path %>
                            </p>
							<table class="datatable">
								<thead>
									 <tr>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Created At
                                        </th>
                                        <th></th>
                                    </tr>
								</thead>
								<tbody>
									<% for design_template in @design_template %>
									<tr class="gradeX">
										<td><%= design_template.name %></td>
										<td><%= design_template.created_at.strftime("%m-%d-%Y") %></td>
										<td><%= link_to "Delete", admin_design_template_path(design_template), :confirm => 'Are you sure?', :method => :delete, :title => "Delete" %></td>
										
									</tr>
									<% end %>
									
								</tbody>
								<tfoot>
									<tr>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Created At
                                        </th>
                                        <th></th>
                                    </tr>
								</tfoot>
							</table>
</div>
</section>
</div>
</article>
<% end %>

app/views/admin/design_templates/new.html.erb
<% content_for :header_meta do%>
<!-- // Meta //  -->
<meta charset="utf-8">   
<meta name="description" content="" />
<meta name="keywords" content="" />

<% end %>
<% content_for :content do %>
	<%= form_for(@design_template, :as => :design_template, :validate => true, :url => admin_design_templates_path) do |f| %>
	
	   <fieldset>
	        <legend><h2>Create Design Template</h2></legend>

	        <dl>
				<dt>
	                <label>Template Name</label>
	            </dt>
	            <dd>
					<%= f.text_field :name, :class => 'small' %>  
	            </dd>
	        </dl>
	        <p>
	            <button type="submit" value="Save">Submit</button> or <a href="/admin/<%= session[:current_page_name].downcase %>" title="Leave without saving" rel="tooltip">Cancel</a>
	        </p>
	        <br />

	    </fieldset>
	<% end %>
	<div>
	    <a href="/admin/<%= session[:current_page_name].downcase %>">Back to List</a>
	</div>
<% end %>